name: build docker images

on:
  push:
    branches:
      [ master ]

jobs:
  job1:
    name: build gs server for cenos6.10
    # 运行所需要的虚拟机环境。它是必填字段
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y%m%d%H%M')"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Debug current directory
        run: |
          pwd
          ls -al
      - name: Build Docker Image
        run: |
          docker buildx build \
            --file ./services/gsserver/Dockerfile \
            --platform linux/amd64 \
            --tag yulinzhihou/centos6.10:latest \
            --tag yulinzhihou/centos6.10:${{ steps.date.outputs.today }} \
            --push \
            ./services/gsserver

      - name: Push Docker image to Docker Hub
        run: |
          docker push -t yulinzhihou/centos6.10:latest \ 
          docker push -t yulinzhihou/centos6.10:${{ steps.date.outputs.today }}


  # job2:
  #   name: build gs server for centos7.10

  # job3:
  #   name: build gs mysql5.1

  # job4:
  #   name: build gs mysql5.7

  # job5:
  #   name: build gs mysql8.0

  # job6:
  #   name: build gs mysql8.1

  # job7:
  #   name: build gs mysql8.4

  # job8:
  #   name: build gs php 5.6

  # job9:
  #   name: build gs php 7.0
  # job10:
  #   name: build gs php 7.1
  # job11:
  #   name: build gs php 7.2
  # job12:
  #   name: build gs php 7.3
  # job13:
  #   name: build gs php 7.4
  # job14:
  #   name: build gs php 8.0
  # job15:
  #   name: build gs php 8.1
  # job16:
  #   name: build gs php 8.2
  # job17:
  #   name: build gs php 8.3
  # job18:
  #   name: build gs php 8.4
  # job19:
  #   name: build gs billing

  # job20:
  #   name: build gs nc clinet for frpc061

  # job21:
  #   name: build gs ns server for frps061

  # job22:
  #   name: build gs nginx for 1.24.0

  # job23:
  #   name: build gs caddy server

  # job24:
  #   name: build gs redis

  # job25:
  #   name: build gs rdkafka
  